namespace Match3.Core
{
    /// <summary>
    /// Special power-up classifications generated by matching combos.
    /// In v0.1, the base mathematical system focuses on None; the enum types
    /// are reserved and prepared for the upcoming special-resolution pass.
    /// </summary>
    public enum TileSpecial : byte
    {
        None = 0,
        RocketHorizontal = 1,
        RocketVertical = 2,
        Dynamite = 3,
        Airstrike = 4
    }
}
